// File generated by FlutLab.
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'try to add using FlutLab Firebase Configuration',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'it not supported by FlutLab yet, but you can add it manually',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'it not supported by FlutLab yet, but you can add it manually',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'it not supported by FlutLab yet, but you can add it manually',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions ios = FirebaseOptions(
      apiKey: 'AIzaSyAjJk2DL2-OtFb_qQAnDykwbvqkc82iuX4',
      iosBundleId: 'com.meding.aldevmus',
      appId: '1:975822733387:ios:6a5d4856557806035a0dce',
      storageBucket: 'meding-aldevmus.firebasestorage.app',
      messagingSenderId: '975822733387',
      iosClientId: 'undefined',
      projectId: 'meding-aldevmus');

  static const FirebaseOptions android = FirebaseOptions(
      apiKey: 'AIzaSyCbqYTNrN0JF1jo_mpgS1swpPdF6GaLQl0',
      appId: '1:975822733387:android:41e7bd428ed0a8a45a0dce',
      messagingSenderId: '975822733387',
      projectId: 'meding-aldevmus',
      storageBucket: 'meding-aldevmus.firebasestorage.app');
}
